webtalk_init -webtalk_dir /home/pin_31d_13/Desktop/msis/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/tb_instr_mem_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May  8 14:14:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "85868e1c-4d39-42e7-a994-8136b26ed44e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "16c3efa4a7be4fafb5a24ce59eca27a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7763 64-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2450.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "137.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9170 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115052_KB" -context "xsim\\usage"
webtalk_transmit -clientid 17285858 -regid "" -xml /home/pin_31d_13/Desktop/msis/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/tb_instr_mem_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/pin_31d_13/Desktop/msis/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/tb_instr_mem_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/pin_31d_13/Desktop/msis/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/tb_instr_mem_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
