#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 08 18:38:47 UTC 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 16c3efa4a7be4fafb5a24ce59eca27a2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_rf_riscv_behav xil_defaultlib.tb_rf_riscv xil_defaultlib.glbl -log elaborate.log"
xelab -wto 16c3efa4a7be4fafb5a24ce59eca27a2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_rf_riscv_behav xil_defaultlib.tb_rf_riscv xil_defaultlib.glbl -log elaborate.log

